---
title: "San Francisco Maps for Comparison"
author: "Jackson M Luckey"
format:
    html:
        embed-resources: true
---

```{r}
library(tidyverse)
library(tidycensus)
library(sf)
```

We'll plot the actual population and unit counts by block in San Francisco.

```{r}
sf_blocks <- get_decennial(
  geography = "block",
  variables = c(
    population = "P1_001N",
    housing_units = "H1_001N"
  ),
  state = "CA",
  county = "San Francisco",
  year = 2020,
  geometry = TRUE
) |>
    pivot_wider(names_from = variable, values_from = value)
```


```{r}
sf_blocks |>
    filter(population > 0) |> # needed because the water and some other random areas are included with population = 0
    mutate(
        area_m2 = st_area(geometry),
        area_km2 = as.numeric(area_m2) / 1e6,
        pop_density = population / area_km2
    ) |>
    mutate(log_pop_density = log10(pop_density)) |>
    ggplot() +
    geom_sf(aes(fill = pop_density), color = NA) +
    scale_fill_viridis_c() +
    theme_minimal()
```